### ISSUE TITLE
Git: invalid path 'Tests/__pycache__/input_generate.cpython-39.pyc:Zone.Identifier'

### ISSUE THREAD

**Issue by eilon-code** [Razi203/data_structures_wet2_tests#1]
Immediately after I cloned the repository, I encountered an error, and the directory to which I cloned is empty except for the .git file. However, after checking, I discovered that it automatically deleted all the files and moved them to staged changes. I managed to discard changes for almost all the files, except for the files ending with the .Zone.Identifier extension.

**Comment by Razi203** [comment]
"Tests/__pycache__/" was uploaded by mistake it is only temporary garbage data you don't need
